---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_port: 22
    ssh_user: root
    ssh_id_path: "~/.ssh/id_ed25519"
  tasks:
    - name: Check if SSH key already exists
      ansible.builtin.stat:
        path: "{{ ssh_id_path }}"
      register: id_ed25519_stat

    - name: Check if SSH public key already exists
      ansible.builtin.stat:
        path: "{{ ssh_id_path }}.pub"
      register: id_ed25519_pub_stat

    - name: Use existing SSH key
      when: id_ed25519_stat.stat.exists
      block:
        - name: Create public SSH key
          ansible.builtin.shell: |
            ssh-keygen -y -f {{ ssh_id_path }} > {{ ssh_id_path }}.pub
          changed_when: false
          when: not id_ed25519_pub_stat.stat.exists

        - name: Register the SSH key facts
          ansible.builtin.set_fact:
            existing_ssh_key_name: "molecule"
            generated_public_ssh_key: "{{ lookup('ansible.builtin.file', ssh_id_path + '.pub') | trim }}"

        - name: Register SSH key for test instance(s)
          vultr.cloud.ssh_key:
            name: "{{ existing_ssh_key_name }}"
            ssh_key: "{{ generated_public_ssh_key }}"
            api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
            state: present
          ignore_errors: true

    - name: Create new SSH key
      when: not id_ed25519_stat.stat.exists
      block:
        - name: Create SSH key
          community.crypto.openssh_keypair:
            path: "{{ ssh_id_path }}"
            force: true
            type: ed25519
          register: generated_ssh_key

        - name: Register the SSH key name
          ansible.builtin.set_fact:
            ssh_key_name: "molecule-generated-{{ 12345 | random | to_uuid }}"

        - name: Register SSH key for test instance(s)
          vultr.cloud.ssh_key:
            name: "{{ ssh_key_name }}"
            ssh_key: "{{ generated_ssh_key.public_key }}"
            api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
            state: present

    - name: Set vultr facts
      ansible.builtin.set_fact:
        vultr_server_state: "{{ lookup('ansible.builtin.env', 'VULTR_SERVER_STATE') or 'present' }}"
        final_ssh_key_name: "{% if id_ed25519_stat.stat.exists %}{{ existing_ssh_key_name }}{% else %}{{ ssh_key_name }}{% endif %}"
        final_ssh_key_path: "{% if id_ed25519_stat.stat.exists %}~/.ssh/id_ed25519{% else %}{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key{% endif %}"

    - name: Print debug output
      ansible.builtin.debug:
        msg:
          - "{{ vultr_server_state }}"
          - "{{ final_ssh_key_name }}"

    - name: Create private network(s)
      vultr.cloud.vpc:
        name: molecule
        v4_subnet: "{{ item.vpc_cidr | ansible.utils.ipaddr('network') }}"
        v4_subnet_mask: "{{ item.vpc_cidr | ansible.utils.ipaddr('prefix') }}"
        region: "{{ item.region }}"
        api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
        state: present
      with_items: "{{ molecule_yml.platforms }}"
      register: networks

    - name: Create molecule instance(s)
      vultr.cloud.instance:
        label: "{{ item.name }}"
        hostname: "{{ item.name }}"
        os: "{{ item.os }}"
        enable_ipv6: yes
        plan: "{{ item.plan }}"
        backups: false
        ddos_protection: false
        region: "{{ item.region }}"
        api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
        ssh_keys:
          - "{{ final_ssh_key_name }}"
        state: "{{ vultr_server_state }}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    - name: Gather instance information when already exists
      vultr.cloud.instance_info:
        api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
      register: existing_instances
      when: vultr_server_state == 'present'

    - name: Populate instance config dict from created instances
      ansible.builtin.set_fact:
        instance_conf_dict:
          {
            "instance": "{{ item.vultr_instance.label }}",
            "ssh_key_name": "{{ final_ssh_key_name }}",
            "address": "{{ item.vultr_instance.main_ip }}",
            "region": "{{ item.vultr_instance.region }}",
            "user": "{{ ssh_user }}",
            "port": "{{ ssh_port }}",
            "identity_file": "{{ final_ssh_key_path }}",
            "networks": "{{ item.item.networks | default({}) | dict2items(key_name='name', value_name='data') }}",
          }
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when:
        - item.vultr_instance | default({}) | length > 0
        - item.changed | bool

    - name: Populate instance config dict from existing instances
      ansible.builtin.set_fact:
        instance_conf_dict:
          {
            "instance": "{{ instance.label }}",
            "ssh_key_name": "{{ final_ssh_key_name }}",
            "address": "{{ instance.main_ip }}",
            "region": "{{ instance.region }}",
            "user": "{{ ssh_user }}",
            "port": "{{ ssh_port }}",
            "identity_file": "{{ final_ssh_key_path }}",
            "networks": "{{ molecule_yml.platforms | selectattr('name', 'equalto', instance.label) | map(attribute='networks') | first | default({}) | dict2items(key_name='name', value_name='data') }}",
          }
      loop: "{{ existing_instances.vultr_instance_info | default([]) }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.label }}"
      register: existing_instance_config_dict
      when:
        - existing_instances is defined
        - existing_instances.vultr_instance_info is defined
        - instance.label in (molecule_yml.platforms | map(attribute='name') | list)

    - name: Convert instance config dict to a list
      ansible.builtin.set_fact:
        instance_conf: "{{ (instance_config_dict.results | default([]) | selectattr('ansible_facts', 'defined') | map(attribute='ansible_facts.instance_conf_dict') | list) + (existing_instance_config_dict.results | default([]) | selectattr('ansible_facts', 'defined') | map(attribute='ansible_facts.instance_conf_dict') | list) }}"
      when: >
        (instance_config_dict.results | default([]) | selectattr('ansible_facts', 'defined') | list | length > 0) or
        (existing_instance_config_dict.results | default([]) | selectattr('ansible_facts', 'defined') | list | length > 0)

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: instance_conf is defined and instance_conf | length > 0

    - name: Dump instance config
      ansible.builtin.debug:
        msg: "content of instance config: {{ lookup('file', molecule_instance_config) | from_yaml }}"
      when: instance_conf is defined and instance_conf | length > 0

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ item.address }}"
        port: "{{ item.port }}"
        search_regex: SSH
        delay: 10
        timeout: 320
      loop: "{{ lookup('file', molecule_instance_config, errors='ignore') | default('[]', true) | from_yaml }}"
      loop_control:
        label: "{{ item.instance }}"
      when: instance_conf is defined and instance_conf | length > 0
