---
name: Ansible Molecule Preparations
description: Run Ansible Molecule Preparations
author: Michael Schmitz

inputs:
  ansible_version:
    description: Ansible version to use, leave empty for newest
    default: ''
  ansible_vault_password:
    description: Ansible Vault Password
    default: ''
  distro:
    description: 'Execute tests against distribution'
    default: 'debian-12'
  molecule_scenario:
    description: Molecule scenario for testing
    default: 'hetznercloud'
  molecule_version:
    description: Molecule version to use, leave empty for newest
    default: ''
  ssh_key:
    description: 'SSH Key to use'
    default: ''
  test_type:
    description: 'Choose between: unit|integration'
    default: 'unit'
  token:
    description: 'Gitea Runner token'
    default: 'unit'

runs:
  using: "composite"
  steps:
    - name: Install rsync
      run: apt-get update -qq -o=Dpkg::Use-Pty=0 && apt-get -qq -o Dpkg::Use-Pty=0 install rsync
      shell: bash

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Check out the molecule repository
      uses: https://github.com/actions/checkout@v4
      with:
        github-server-url: https://git.msqu.de
        repository: cicd/molecule
        token: ${{ inputs.token }}
        path: 'git_molecule'
        ref: 'main'
        fetch-depth: 0

    - name: Check out the infra repository
      uses: https://github.com/actions/checkout@v4
      with:
        github-server-url: https://git.msqu.de
        repository: infrastructure/infra
        token: ${{ inputs.token }}
        path: 'git_infra'
        ref: 'main'
        fetch-depth: 0
        sparse-checkout: |
          requirements
          group_vars

    - name: Set CI_HOSTNAME / CI_PROJECT_NAME_MOLECULE
      run: |
        echo "CI_HOSTNAME=$(echo $MOLECULE_DISTRO | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "CI_PROJECT_NAME_MOLECULE=$(echo ${GITHUB_REPOSITORY#*/} | tr '_' '-')" >> $GITHUB_ENV
      shell: bash
      env:
        MOLECULE_DISTRO: "${{ inputs.distro }}"

    - name: Prepare Ansible Vault
      run: echo "${{ inputs.ansible_vault_password }}" > "$GITHUB_WORKSPACE/.vault"
      shell: bash

    - name: Prepare SSH Key
      if: "${{ inputs.ssh_key }} != '' }}"
      run: |
        mkdir -p ~/.ssh/ && echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        eval "$(ssh-agent -s)" && echo "${{ inputs.ssh_key }}" | tr -d '\r' | ssh-add - >/dev/null
      shell: bash

    - name: Prepare Molecule Scenario
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/molecule/default
        rsync -avzh --ignore-existing --ignore-errors git_molecule/scenarios/${{ inputs.molecule_scenario }}/ ${GITHUB_WORKSPACE}/molecule/default/
      shell: bash

    - name: Sync vars
      run: |
        if [[ "${{ inputs.test_type }}" == "unit" ]] && [[ -f "${GITHUB_WORKSPACE}/tests/vars.yml" ]]; then
          mkdir -p ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/ && rsync -aP ${GITHUB_WORKSPACE}/tests/vars.yml ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/test_vars.yml
        elif [[ "${{ inputs.test_type }}" == "integration" ]]; then
          rsync -aP git_infra/group_vars ${GITHUB_WORKSPACE}/molecule/default/
        fi
      shell: bash

    - name: Install software via pip
      run: pip install 'ansible-core${{ inputs.ansible_version }}' 'molecule${{ inputs.molecule_version }}' netaddr jmespath dnspython python-dateutil Jinja2 requests --break-system-packages --quiet
      shell: bash

    - name: Install collections from collections.yml
      run: ansible-galaxy install -r git_infra/requirements/collections_git.yml
      shell: bash
