name: Prepare Molecule
description: Prepare environment for Ansible Molecule testing
author: Michael Schmitz

inputs:
  molecule_scenario:
    description: Molecule scenario for testing
    default: "hetznercloud"
  ssh_key:
    description: SSH Key content to use (pass as workflow input)
    default: ''
  token:
    description: Gitea Runner token
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install rsync
      run: |
        apt-get update -qq -o=Dpkg::Use-Pty=0
        apt-get -qq -o Dpkg::Use-Pty=0 install rsync
      shell: bash

    - name: Setup Python
      uses: https://github.com/actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Prepare SSH Key
      if: ${{ inputs.ssh_key != '' }}
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519
      shell: bash

    - name: Install software via pip
      run: |
        pip install ansible-core molecule netaddr jmespath dnspython python-dateutil Jinja2 requests \
        --break-system-packages --quiet
      shell: bash

    - name: Checkout infra repository
      uses: https://github.com/actions/checkout@v5
      with:
        github-server-url: https://git.msqu.de
        repository: infrastructure/infra
        token: '${{ inputs.token }}'
        path: git_infra
        ref: main
        fetch-depth: 0
        sparse-checkout: |
          requirements/

    - name: Install collections from collections_git.yml
      run: ansible-galaxy install -r git_infra/requirements/collections_git.yml
      shell: bash
