---
name: Ansible Molecule Preparations
description: Run Ansible Molecule Preparations
author: Michael Schmitz

inputs:
  ansible_version:
    description: Ansible version to use, leave empty for newest
    default: ''
  molecule_scenario:
    description: Molecule scenario for testing
    default: 'hetznercloud'
  molecule_version:
    description: Molecule version to use, leave empty for newest
    default: ''
  ssh_key:
    description: 'SSH Key to use'
    default: '${{ secrets.SSH_PRIVATE_KEY }}'
  token:
    description: 'Gitea Runner token'
    default: 'unit'

runs:
  using: "composite"
  steps:
    - name: Install rsync
      run: apt-get update -qq -o=Dpkg::Use-Pty=0 && apt-get -qq -o Dpkg::Use-Pty=0 install rsync
      shell: bash

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare SSH Key
      if: "${{ inputs.ssh_key }} != '' }}"
      run: |
        mkdir -p ~/.ssh/ && echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        eval "$(ssh-agent -s)" && echo "${{ inputs.ssh_key }}" | tr -d '\r' | ssh-add - >/dev/null
      shell: bash

    - name: Install software via pip
      run: pip install 'ansible-core${{ inputs.ansible_version }}' 'molecule${{ inputs.molecule_version }}' netaddr jmespath dnspython python-dateutil Jinja2 requests --break-system-packages --quiet
      shell: bash

    - name: Check out the infra repository requirements/collections_git.yml
      uses: https://github.com/actions/checkout@v4
      with:
        github-server-url: https://git.msqu.de
        repository: infrastructure/infra
        token: ${{ inputs.token }}
        path: 'git_infra'
        ref: 'main'
        fetch-depth: 0
        sparse-checkout: |
          requirements/collections_git.yml

    - name: Install collections from collections.yml
      run: ansible-galaxy install -r git_infra/requirements/collections_git.yml
      shell: bash
