_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageDocker.yml


kind: pipeline
name: default

steps:
  - <<: *ContainerImageDocker
    name: ansible
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "ansible"
      DOCKERFILE: ./Ansible
      DOCKER_ARGS: "--build-arg FROM=python:3-alpine"

  - <<: *ContainerImageDocker
    name: ansible-dind
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "ansible-dind"
      DOCKERFILE: ./DinD
      DOCKER_ARGS: "--build-arg FROM=docker:dind"

  - <<: *ContainerImageDocker
    name: archlinux
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "archlinux"
      DOCKERFILE: ./Archlinux

  - <<: *ContainerImageDocker
    name: lint
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "lint"
      DOCKERFILE: ./Lint

  - <<: *ContainerImageDocker
    name: debian-10
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "debian-10"
      DOCKERFILE: ./Debian
      DOCKER_ARGS: "--build-arg OS_VERSION=buster"

  - <<: *ContainerImageDocker
    name: debian-11
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "debian-11"
      DOCKERFILE: ./Debian
      DOCKER_ARGS: "--build-arg OS_VERSION=bullseye"

  - <<: *ContainerImageDocker
    name: debian-12
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "debian-12"
      DOCKERFILE: ./Debian
      DOCKER_ARGS: "--build-arg OS_VERSION=bookworm"

  - <<: *ContainerImageDocker
    name: ubuntu-20.04
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "ubuntu-20.04"
      DOCKERFILE: ./Ubuntu
      DOCKER_ARGS: "--build-arg OS_VERSION=20.04"

  - <<: *ContainerImageDocker
    name: ubuntu-22.04
    depends_on: [ clone ]
    environment:
      TAG_EXPLICIT: "ubuntu-22.04"
      DOCKERFILE: ./Ubuntu
      DOCKER_ARGS: "--build-arg OS_VERSION=22.04"

services:
  - <<: *ContainerImageDockerDinDService
    name: svc_docker_dind

volumes:
  - <<: *ContainerImageDockerVolume
