_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageKaniko.yml

kind: pipeline
name: default

steps:

- <<: *ContainerImageKaniko
  name: ansible
  environment:
    ADDITIONAL_REGISTRY_DESTINATIONS: "python:3-alpine"
    DOCKERFILE: ./Ansible
    KANIKO_ARGS: "--build-arg VERSION=python:3-alpine"
