_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageDocker.yml


kind: pipeline
name: infra

steps:
  - <<: *ContainerImageDocker
    name: lint
    depends_on: [ clone ]
    environment:
      DOCKER_ARGS: "--build-arg ANSIBLE_LINT_VERSION=latest"
      DOCKERFILE: ./Lint
      TAG_EXPLICIT: "lint"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/molecule:"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: ansible
    depends_on: [ clone ]
    environment:
      DOCKER_ARGS: "--build-arg FROM=python:3-alpine"
      DOCKERFILE: ./Ansible
      TAG_EXPLICIT: "ansible"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/molecule:"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: ansible-dind
    depends_on: [ clone ]
    environment:
      DOCKER_ARGS: "--build-arg FROM=docker:dind"
      DOCKERFILE: ./DinD
      TAG_EXPLICIT: "ansible-dind"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/molecule:"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

services:
  - <<: *ContainerImageDockerDinDService
    name: svc_docker_dind

volumes:
  - <<: *ContainerImageDockerVolume

---
_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/Molecule.yml

kind: pipeline
name: molecule

steps:

  - <<: *MoleculeDind
    name: unit_debian-11
    environment:
      <<: *global-variables
      MOLECULE_DISTRO: "debian-11"
      TEST_TYPE: unit
      MOLECULE_SCENARIO_NAME: docker

  - <<: *MoleculeDind
    name: unit_debian-10
    environment:
      <<: *global-variables
      MOLECULE_DISTRO: "debian-10"
      TEST_TYPE: unit
      MOLECULE_SCENARIO_NAME: docker

  - <<: *MoleculeDind
    name: unit_ubuntu-2204
    environment:
      <<: *global-variables
      MOLECULE_DISTRO: "ubuntu-22.04"
      TEST_TYPE: unit
      MOLECULE_SCENARIO_NAME: docker

  - <<: *MoleculeDind
    name: unit_ubuntu-2004
    environment:
      <<: *global-variables
      MOLECULE_DISTRO: "ubuntu-20.04"
      TEST_TYPE: unit
      MOLECULE_SCENARIO_NAME: docker

services:
  - <<: *ContainerImageDockerDinDService
    name: svc_docker_dind

volumes:
  - <<: *ContainerImageDockerVolume
