_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageKaniko.yml

kind: pipeline
name: default

steps:

- <<: *ContainerImageKaniko
  name: lint
  environment:
    ADDITIONAL_REGISTRY_DESTINATIONS: "lint"
    DOCKERFILE: ./Lint
