---
image: docker:stable

services:
- name: docker:dind
  command: ["--experimental"]

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  # Enable experimental features in Docker client
  - mkdir $HOME/.docker
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # login to gitlab ci
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}

.build-template: &build-template
  stage: build
  script:
    - >
      docker build \
        --squash \
        --build-arg VERSION=${VERSION:-"latest"} \
        --tag $CONTAINER_IMAGE:$IMAGE_TAG \
        -f ${DOCKERFILE:-./Dockerfile} \
        .
    - docker push $CONTAINER_IMAGE:$IMAGE_TAG

build-ansible:
  <<: *build-template
  variables:
    IMAGE_TAG: "ansible"
    DOCKERFILE: ./Ansible
    VERSION: "python:3-alpine"

build-ansible-dind:
  <<: *build-template
  variables:
    IMAGE_TAG: "ansible-dind"
    DOCKERFILE: ./Ansible
    VERSION: "docker:dind"

build-archlinux:
  <<: *build-template
  variables:
    IMAGE_TAG: "archlinux"
    DOCKERFILE: ./Archlinux

build-debian-10:
  <<: *build-template
  variables:
    IMAGE_TAG: "debian-10"
    DOCKERFILE: ./Debian
    VERSION: "10"

build-debian-11:
  <<: *build-template
  variables:
    IMAGE_TAG: "debian-11"
    DOCKERFILE: ./Debian
    VERSION: "bullseye"

build-debian-12:
  <<: *build-template
  variables:
    IMAGE_TAG: "debian-12"
    DOCKERFILE: ./Debian
    VERSION: "bookworm"

build-lint:
  <<: *build-template
  variables:
    IMAGE_TAG: "lint"
    DOCKERFILE: ./Lint

build-ubuntu-2004:
  <<: *build-template
  variables:
    IMAGE_TAG: "ubuntu-20.04"
    DOCKERFILE: ./Ubuntu
    VERSION: "20.04"

build-ubuntu-2204:
  <<: *build-template
  variables:
    IMAGE_TAG: "ubuntu-22.04"
    DOCKERFILE: ./Ubuntu
    VERSION: "22.04"
