---
image: docker:stable

services:
- name: docker:dind
  command: ["--experimental"]

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  # Enable experimental features in Docker client
  - mkdir $HOME/.docker
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # login to gitlab ci
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}

.build-template: &build-template
  stage: build
  script:
    - >
      docker build \
        --squash \
        --tag $CONTAINER_IMAGE:$IMAGE_TAG \
        -f ${DOCKERFILE:-./Dockerfile} \
        .
    - docker push $CONTAINER_IMAGE:$IMAGE_TAG

build-ansible:
  <<: *build-template
  variables:
    IMAGE_TAG: "ansible"
    DOCKERFILE: ./Ansible

build-ansible-lint:
  <<: *build-template
  variables:
    IMAGE_TAG: "ansible-lint"
    DOCKERFILE: ./Ansible-Lint

build-debian-10:
  <<: *build-template
  variables:
    IMAGE_TAG: "debian-10"
    DOCKERFILE: ./Debian-10

build-debian-11:
  <<: *build-template
  variables:
    IMAGE_TAG: "debian-11"
    DOCKERFILE: ./Debian-11

build-ubuntu-1804:
  <<: *build-template
  variables:
    IMAGE_TAG: "ubuntu-1804"
    DOCKERFILE: ./Ubuntu-1804

build-ubuntu-2004:
  <<: *build-template
  variables:
    IMAGE_TAG: "ubuntu-2004"
    DOCKERFILE: ./Ubuntu-2004
