---
name: Ansible Molecule
description: Run Ansible Molecule
author: Michael Schmitz

inputs:
  args:
    description: 'Additional arguments passed to molecule test'
    default: ''
  ansible_version:
    description: Ansible version to use, leave empty for newest
    default: ''
  ansible_vault_password:
    description: Ansible Vault Password
    default: ''
  distro:
    description: 'Execute tests against distribution'
    default: 'debian-12'
  hcloud_token:
    description: 'Hetzner API Token'
    default: ''
  hcloud_server_state:
    description: 'Server State after Molecule run'
    default: 'absent'
  molecule_debug:
    description: Whether to tell the GitHub client to log details of its requests
    default: ${{ (env.RUNNER_DEBUG == '1' && 'true') || 'false' }}
  molecule_scenario:
    description: Molecule scenario for testing
    default: 'hetznercloud'
  molecule_version:
    description: Molecule version to use, leave empty for newest
    default: ''
  ssh_key:
    description: 'SSH Key to use'
    default: ''
  test_type:
    description: 'Choose between: unit|integration'
    default: 'unit'
  token:
    description: 'Gitea Runner token'
    default: 'unit'

runs:
  using: "composite"
  steps:
    - name: Install rsync
      run: apt-get update -qq -o=Dpkg::Use-Pty=0 && apt-get -qq -o Dpkg::Use-Pty=0 install rsync
      shell: bash

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Check out the molecule repository
      uses: https://github.com/actions/checkout@v4
      with:
        github-server-url: https://git.msqu.de
        repository: cicd/molecule
        token: ${{ inputs.token }}
        path: 'git_molecule'
        ref: 'main'
        fetch-depth: 0

    - name: Check out the infra repository
      uses: https://github.com/actions/checkout@v4
      with:
        github-server-url: https://git.msqu.de
        repository: infrastructure/infra
        token: ${{ inputs.token }}
        path: 'git_infra'
        ref: 'main'
        fetch-depth: 0
        sparse-checkout: |
          requirements
          group_vars

    - name: Set CI_HOSTNAME / CI_PROJECT_NAME_MOLECULE
      run: |
        echo "CI_HOSTNAME=$(echo $MOLECULE_DISTRO | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "CI_PROJECT_NAME_MOLECULE=$(echo ${GITHUB_REPOSITORY#*/} | tr '_' '-')" >> $GITHUB_ENV
      shell: bash
      env:
        MOLECULE_DISTRO: "${{ inputs.distro }}"

    - name: Prepare Ansible Vault
      run: echo "${{ inputs.ansible_vault_password }}" > "$GITHUB_WORKSPACE/.vault"
      shell: bash

    - name: Prepare SSH Key
      if: "${{ inputs.ssh_key }} != '' }}"
      run: |
        mkdir -p ~/.ssh/ && echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        eval "$(ssh-agent -s)" && echo "${{ inputs.ssh_key }}" | tr -d '\r' | ssh-add - >/dev/null
      shell: bash

    - name: Prepare Molecule Scenario
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/molecule/default
        rsync -avzh --ignore-existing --ignore-errors git_molecule/scenarios/${{ inputs.molecule_scenario }}/ ${GITHUB_WORKSPACE}/molecule/default/
      shell: bash

    - name: Sync vars
      run: |
        if [[ "${{ inputs.test_type }}" == "unit" ]] && [[ -f "${GITHUB_WORKSPACE}/tests/vars.yml" ]]; then
          mkdir -p ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/ && rsync -aP ${GITHUB_WORKSPACE}/tests/vars.yml ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/test_vars.yml
        elif [[ "${{ inputs.test_type }}" == "integration" ]]; then
          rsync -aP git_infra/group_vars ${GITHUB_WORKSPACE}/molecule/default/
        fi
      shell: bash

    - name: Update requirements.yml
      run: |
        if [ -f "${GITHUB_WORKSPACE}/requirements.yml" ]; then sed -i "s,ssh://git@git.msqu.de:22222/.*/,https://${{ inputs.token }}@github.com/${GITHUB_REPOSITORY_OWNER}/,g" ${GITHUB_WORKSPACE}/requirements.yml; fi
      shell: bash

    - name: Install software via pip
      run: pip install 'ansible-core${{ inputs.ansible_version }}' 'molecule${{ inputs.molecule_version }}' netaddr jmespath dnspython python-dateutil Jinja2 requests --break-system-packages --quiet
      shell: bash

    - name: Pip list
      if: runner.debug == '1'
      run: pip list
      shell: bash

    - name: Install collections from collections.yml
      run: ansible-galaxy install -r git_infra/requirements/collections_git.yml
      shell: bash

    - name: Print molecule version infos
      if: runner.debug == '1'
      run: molecule --version
      shell: bash

    - name: Print installed ansible collections
      if: runner.debug == '1'
      run: ansible-galaxy collection list
      shell: bash

    - name: Setup tmate session
      if: runner.debug == '1'
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true

    - name: Run Molecule tests
      run: molecule test ${{ inputs.args }}
      shell: bash
      env:
        ANSIBLE_FORCE_COLOR: '1'
        ANSIBLE_VERBOSITY: '2'
        CI_JOB_ID: "${{ github.run_id }}"
        CI_PROJECT_DIR: "$GITHUB_WORKSPACE"
        GITEA_TOKEN: "${{ inputs.token }}"
        HCLOUD_SERVER_STATE: "${{ inputs.hcloud_server_state }}"
        HCLOUD_TOKEN: "${{ inputs.hcloud_token }}"
        MOLECULE_DEBUG: "${{ inputs.molecule_debug }}"
        MOLECULE_DISTRO: "${{ inputs.distro }}"
        MOLECULE_SCENARIO_NAME: "${{ inputs.molecule_scenario }}"
        PY_COLORS: '1'
        TEST_TYPE: "${{ inputs.test_type }}"
