name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  json-yaml-validate:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v7

      - name: json-yaml-validate
        uses: https://github.com/GrantBirki/json-yaml-validate.git@250fa0dc7d7f4a888b24dc2a6b2ff589753fba70  # v3.3.2

  lint:
    runs-on: molecule
    container:
      image: ghcr.io/msqu-devops/molecule:runner@sha256:a15b2531cd7b7fa99e22e44a09b48c1b5484165970e568e92d50aa32c784c5e4
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v7

      - name: Ansible Lint scenarios
        run: ansible-lint --offline scenarios/

      - name: Yaml Lint
        run: yamllint -f colored scenarios .gitea
