---
name: Docker build and push

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Lint
            tags: lint
            build-args: "ANSIBLE_LINT_VERSION=latest"
          - dockerfile: Ansible
            tags: ansible
            build-args: "FROM=python:3-alpine"
          - dockerfile: DinD
            tags: ansible-dind
            build-args: "FROM=docker:dind"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: gitea.msqu.de
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.PAT}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles
          file: ./dockerfiles${{ matrix.dockerfile }}
          build-args: ${{ matrix.build-args }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
          platforms: linux/amd64,linux/arm64
