---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: debian-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    server_type: cx11
    image: debian-10
  - name: ubuntu-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    server_type: cx11
    image: ubuntu-20.04
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
