---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-10-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:debian-10
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
  - name: debian-11-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:debian-11
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
  - name: ubuntu-1804-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:ubuntu-1804
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
  - name: ubuntu-2004-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:ubuntu-2004
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
