---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-${CI_PROJECT_NAME_MOLECULE}
    image: schmitzis/molecule:${MOLECULE_DISTRO}
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: yes
      callbacks_enabled: ansible.posix.timer, ansible.posix.profile_tasks
      display_failed_stderr: true
      host_key_checking: false
      remote_tmp: '/tmp/.ansible-${USER}/tmp'
      callback_result_format: yaml
      vault_password_file: ${CI_PROJECT_DIR}/.vault
    diff:
      always: true
    callback_profile_tasks:
      task_output_limit: all
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK_PREPARE:-prepare.yml}
    cleanup: ${MOLECULE_PLAYBOOK_CLEANUP:-cleanup.yml}
    converge: ${MOLECULE_PLAYBOOK_CONVERGE:-converge.yml}
    destroy: ${MOLECULE_PLAYBOOK_DESTROY:-destroy.yml}
  log: True
verifier:
  name: ansible
