---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-${CI_PROJECT_NAME}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:debian-10
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible.builtin.command: /lib/systemd/systemd
  - name: ubuntu-${CI_PROJECT_NAME}-${CI_JOB_ID}
    image: registry.gitlab.com/ms-it/molecule:ubuntu-2004
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible.builtin.command: /lib/systemd/systemd
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
