---
name: ci

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - master
      - unicorn
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - os: "Ubuntu"
            version: "20.04"
          - os: "Ubuntu"
            version: "22.04"
          - os: "Debian"
            version: "bullseye"
          - os: "Debian"
            version: "bookworm"
          - os: "Ansible"
            version: "ansible"
          - os: "DinD"
            version: "docker:dind"
          - os: "Archlinux"
            version: "archlinux"
          - os: "Lint"
            version: "lint"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }},enable={{is_default_branch}}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: '${{ matrix.os }}'
          build-args: OS_VERSION=${{ matrix.version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
